spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${SOF_GOOGLE_CLIENT_ID}
            clientSecret: ${SOF_GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          github:
            clientId: ${SOF_GITHUB_CLIENT_ID}
            clientSecret: ${SOF_GITHUB_CLIENT_SECRET}
            scope:
              - read:user
server:
  servlet:
    encoding:
      force-response: true
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 60
  refresh-token-expiration-days: 7
aws-s3:
  access-key: ${AWS_S3_ACCESS_KEY}
  secret-access-key: ${AWS_S3_SECRET_ACCESS_KEY}
config:
  domain: all